import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the ticketing application
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/events">
            <a className={styles.card}>
              <h2>Events &rarr;</h2>
              <p>Explore available events</p>
            </a>
          </Link>

          <Link href="/tickets">
            <a className={styles.card}>
              <h2>Tickets &rarr;</h2>
              <p>Manage your tickets</p>
            </a>
          </Link>


          <Link href="/profile">
            <a className={styles.card}>
              <h2>Profile &rarr;</h2>
              <p>Manage your profile</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img src="/vercel.svg" alt="Vercel Logo" className={styles.logo} />
        </a>
      </footer>
    </div>
  );
}
